"use client";
// import type { Metadata } from "next";
import "@/app/styles/app.css";
import { Toaster } from "sonner";
import ReactQueryProvider from "../../providers/ReactQueryProvider";
import { AppThemeProvider } from "../../providers/AppThemeProvider";
import { useTheme } from "next-themes";

// export const metadata: Metadata = {
//   title: "Stellance - App",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { resolvedTheme } = useTheme();

  return (
    <AppThemeProvider>
      <ReactQueryProvider>
        <div className={`body ${resolvedTheme === "dark" ? "dark" : ""}`}>
          <div className="min-h-screen relative">{children}</div>
          <Toaster position="top-right" richColors theme="system" />
        </div>
      </ReactQueryProvider>
    </AppThemeProvider>
  );
}
