"use client";
// import type { Metadata } from "next";
import "@/app/styles/app.css";
import { Toaster } from "sonner";
import ReactQueryProvider from "../../providers/ReactQueryProvider";
import { useEffect } from "react";
import { useVariableStore } from "../../store/variables";

// export const metadata: Metadata = {
//   title: "Stellance - App",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { initializeTheme, theme } = useVariableStore();
            // const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;

            // console.log("Current theme:", prefersDark ? "dark" : "light");

  useEffect(() => {
    initializeTheme();
  }, [initializeTheme]);

  return (
    <ReactQueryProvider>
      <div className={`body ${theme === "dark" ? "dark" : ""}`}>
        <div className="min-h-screen relative">{children}</div>
        <Toaster position="top-right" richColors theme="system" />
      </div>
    </ReactQueryProvider>
  );
}
