import type { Metadata } from "next";
import "@/app/styles/app.css";
import { Toaster } from "sonner";
import ReactQueryProvider from "../../providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Stellance - App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <div className="body dak ">
        <div className="min-h-screen relative">{children}</div>
        <Toaster position="top-right" richColors theme="system" />
      </div>
    </ReactQueryProvider>
  );
}
