import type { Metadata } from "next";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Stellance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={``}>{children}</body>
    </html>
  );
}
