export const countryCodes = [
  { country: "Afghanistan", code: "+93", abb: "AF" },
  { country: "Albania", code: "+355", abb: "AL" },
  { country: "Algeria", code: "+213", abb: "DZ" },
  { country: "Andorra", code: "+376", abb: "AD" },
  { country: "Angola", code: "+244", abb: "AO" },
  { country: "Argentina", code: "+54", abb: "AR" },
  { country: "Armenia", code: "+374", abb: "AM" },
  { country: "Australia", code: "+61", abb: "AU" },
  { country: "Austria", code: "+43", abb: "AT" },
  { country: "Bahamas", code: "+1-242", abb: "BS" },
  { country: "Bahrain", code: "+973", abb: "BH" },
  { country: "Bangladesh", code: "+880", abb: "BD" },
  { country: "Barbados", code: "+1-246", abb: "BB" },
  { country: "Belarus", code: "+375", abb: "BY" },
  { country: "Belgium", code: "+32", abb: "BE" },
  { country: "Belize", code: "+501", abb: "BZ" },
  { country: "Benin", code: "+229", abb: "BJ" },
  { country: "Bhutan", code: "+975", abb: "BT" },
  { country: "Bolivia", code: "+591", abb: "BO" },
  { country: "Bosnia and Herzegovina", code: "+387", abb: "BA" },
  { country: "Botswana", code: "+267", abb: "BW" },
  { country: "Brazil", code: "+55", abb: "BR" },
  { country: "Brunei", code: "+673", abb: "BN" },
  { country: "Bulgaria", code: "+359", abb: "BG" },
  { country: "Burkina Faso", code: "+226", abb: "BF" },
  { country: "Burundi", code: "+257", abb: "BI" },
  { country: "Cambodia", code: "+855", abb: "KH" },
  { country: "Cameroon", code: "+237", abb: "CM" },
  { country: "Canada", code: "+1", abb: "CA" },
  { country: "Cape Verde", code: "+238", abb: "CV" },
  { country: "Central African Republic", code: "+236", abb: "CF" },
  { country: "Chad", code: "+235", abb: "TD" },
  { country: "Chile", code: "+56", abb: "CL" },
  { country: "China", code: "+86", abb: "CN" },
  { country: "Colombia", code: "+57", abb: "CO" },
  { country: "Comoros", code: "+269", abb: "KM" },
  { country: "Congo (DRC)", code: "+243", abb: "CD" },
  { country: "Congo (Republic)", code: "+242", abb: "CG" },
  { country: "Costa Rica", code: "+506", abb: "CR" },
  { country: "Croatia", code: "+385", abb: "HR" },
  { country: "Cuba", code: "+53", abb: "CU" },
  { country: "Cyprus", code: "+357", abb: "CY" },
  { country: "Czech Republic", code: "+420", abb: "CZ" },
  { country: "Denmark", code: "+45", abb: "DK" },
  { country: "Djibouti", code: "+253", abb: "DJ" },
  { country: "Dominica", code: "+1-767", abb: "DM" },
  { country: "Dominican Republic", code: "+1-809", abb: "DO" },
  { country: "Ecuador", code: "+593", abb: "EC" },
  { country: "Egypt", code: "+20", abb: "EG" },
  { country: "El Salvador", code: "+503", abb: "SV" },
  { country: "Equatorial Guinea", code: "+240", abb: "GQ" },
  { country: "Eritrea", code: "+291", abb: "ER" },
  { country: "Estonia", code: "+372", abb: "EE" },
  { country: "Eswatini", code: "+268", abb: "SZ" },
  { country: "Ethiopia", code: "+251", abb: "ET" },
  { country: "Fiji", code: "+679", abb: "FJ" },
  { country: "Finland", code: "+358", abb: "FI" },
  { country: "France", code: "+33", abb: "FR" },
  { country: "Gabon", code: "+241", abb: "GA" },
  { country: "Gambia", code: "+220", abb: "GM" },
  { country: "Georgia", code: "+995", abb: "GE" },
  { country: "Germany", code: "+49", abb: "DE" },
  { country: "Ghana", code: "+233", abb: "GH" },
  { country: "Greece", code: "+30", abb: "GR" },
  { country: "Grenada", code: "+1-473", abb: "GD" },
  { country: "Guatemala", code: "+502", abb: "GT" },
  { country: "Guinea", code: "+224", abb: "GN" },
  { country: "Guinea-Bissau", code: "+245", abb: "GW" },
  { country: "Guyana", code: "+592", abb: "GY" },
  { country: "Haiti", code: "+509", abb: "HT" },
  { country: "Honduras", code: "+504", abb: "HN" },
  { country: "Hungary", code: "+36", abb: "HU" },
  { country: "Iceland", code: "+354", abb: "IS" },
  { country: "India", code: "+91", abb: "IN" },
  { country: "Indonesia", code: "+62", abb: "ID" },
  { country: "Iran", code: "+98", abb: "IR" },
  { country: "Iraq", code: "+964", abb: "IQ" },
  { country: "Ireland", code: "+353", abb: "IE" },
  { country: "Israel", code: "+972", abb: "IL" },
  { country: "Italy", code: "+39", abb: "IT" },
  { country: "Jamaica", code: "+1-876", abb: "JM" },
  { country: "Japan", code: "+81", abb: "JP" },
  { country: "Jordan", code: "+962", abb: "JO" },
  { country: "Kazakhstan", code: "+7", abb: "KZ" },
  { country: "Kenya", code: "+254", abb: "KE" },
  { country: "Kiribati", code: "+686", abb: "KI" },
  { country: "Kuwait", code: "+965", abb: "KW" },
  { country: "Kyrgyzstan", code: "+996", abb: "KG" },
  { country: "Laos", code: "+856", abb: "LA" },
  { country: "Latvia", code: "+371", abb: "LV" },
  { country: "Lebanon", code: "+961", abb: "LB" },
  { country: "Lesotho", code: "+266", abb: "LS" },
  { country: "Liberia", code: "+231", abb: "LR" },
  { country: "Libya", code: "+218", abb: "LY" },
  { country: "Liechtenstein", code: "+423", abb: "LI" },
  { country: "Lithuania", code: "+370", abb: "LT" },
  { country: "Luxembourg", code: "+352", abb: "LU" },
  { country: "Madagascar", code: "+261", abb: "MG" },
  { country: "Malawi", code: "+265", abb: "MW" },
  { country: "Malaysia", code: "+60", abb: "MY" },
  { country: "Maldives", code: "+960", abb: "MV" },
  { country: "Mali", code: "+223", abb: "ML" },
  { country: "Malta", code: "+356", abb: "MT" },
  { country: "Marshall Islands", code: "+692", abb: "MH" },
  { country: "Mauritania", code: "+222", abb: "MR" },
  { country: "Mauritius", code: "+230", abb: "MU" },
  { country: "Mexico", code: "+52", abb: "MX" },
  { country: "Micronesia", code: "+691", abb: "FM" },
  { country: "Moldova", code: "+373", abb: "MD" },
  { country: "Monaco", code: "+377", abb: "MC" },
  { country: "Mongolia", code: "+976", abb: "MN" },
  { country: "Montenegro", code: "+382", abb: "ME" },
  { country: "Morocco", code: "+212", abb: "MA" },
  { country: "Mozambique", code: "+258", abb: "MZ" },
  { country: "Myanmar", code: "+95", abb: "MM" },
  { country: "Namibia", code: "+264", abb: "NA" },
  { country: "Nauru", code: "+674", abb: "NR" },
  { country: "Nepal", code: "+977", abb: "NP" },
  { country: "Netherlands", code: "+31", abb: "NL" },
  { country: "New Zealand", code: "+64", abb: "NZ" },
  { country: "Nicaragua", code: "+505", abb: "NI" },
  { country: "Niger", code: "+227", abb: "NE" },
  { country: "Nigeria", code: "+234", abb: "NG" },
  { country: "North Macedonia", code: "+389", abb: "MK" },
  { country: "Norway", code: "+47", abb: "NO" },
  { country: "Oman", code: "+968", abb: "OM" },
  { country: "Pakistan", code: "+92", abb: "PK" },
  { country: "Palau", code: "+680", abb: "PW" },
  { country: "Panama", code: "+507", abb: "PA" },
  { country: "Papua New Guinea", code: "+675", abb: "PG" },
  { country: "Paraguay", code: "+595", abb: "PY" },
  { country: "Peru", code: "+51", abb: "PE" },
  { country: "Philippines", code: "+63", abb: "PH" },
  { country: "Poland", code: "+48", abb: "PL" },
  { country: "Portugal", code: "+351", abb: "PT" },
  { country: "Qatar", code: "+974", abb: "QA" },
  { country: "Romania", code: "+40", abb: "RO" },
  { country: "Russia", code: "+7", abb: "RU" },
  { country: "Rwanda", code: "+250", abb: "RW" },
  { country: "Samoa", code: "+685", abb: "WS" },
  { country: "San Marino", code: "+378", abb: "SM" },
  { country: "Saudi Arabia", code: "+966", abb: "SA" },
  { country: "Senegal", code: "+221", abb: "SN" },
  { country: "Serbia", code: "+381", abb: "RS" },
  { country: "Seychelles", code: "+248", abb: "SC" },
  { country: "Sierra Leone", code: "+232", abb: "SL" },
  { country: "Singapore", code: "+65", abb: "SG" },
  { country: "Slovakia", code: "+421", abb: "SK" },
  { country: "Slovenia", code: "+386", abb: "SI" },
  { country: "Solomon Islands", code: "+677", abb: "SB" },
  { country: "Somalia", code: "+252", abb: "SO" },
  { country: "South Africa", code: "+27", abb: "ZA" },
  { country: "South Korea", code: "+82", abb: "KR" },
  { country: "South Sudan", code: "+211", abb: "SS" },
  { country: "Spain", code: "+34", abb: "ES" },
  { country: "Sri Lanka", code: "+94", abb: "LK" },
  { country: "Sudan", code: "+249", abb: "SD" },
  { country: "Suriname", code: "+597", abb: "SR" },
  { country: "Sweden", code: "+46", abb: "SE" },
  { country: "Switzerland", code: "+41", abb: "CH" },
  { country: "Syria", code: "+963", abb: "SY" },
  { country: "Taiwan", code: "+886", abb: "TW" },
  { country: "Tajikistan", code: "+992", abb: "TJ" },
  { country: "Tanzania", code: "+255", abb: "TZ" },
  { country: "Thailand", code: "+66", abb: "TH" },
  { country: "Togo", code: "+228", abb: "TG" },
  { country: "Tonga", code: "+676", abb: "TO" },
  { country: "Trinidad and Tobago", code: "+1-868", abb: "TT" },
  { country: "Tunisia", code: "+216", abb: "TN" },
  { country: "Turkey", code: "+90", abb: "TR" },
  { country: "Turkmenistan", code: "+993", abb: "TM" },
  { country: "Tuvalu", code: "+688", abb: "TV" },
  { country: "Uganda", code: "+256", abb: "UG" },
  { country: "Ukraine", code: "+380", abb: "UA" },
  { country: "United Arab Emirates", code: "+971", abb: "AE" },
  { country: "United Kingdom", code: "+44", abb: "GB" },
  { country: "United States", code: "+1", abb: "US" },
  { country: "Uruguay", code: "+598", abb: "UY" },
  { country: "Uzbekistan", code: "+998", abb: "UZ" },
  { country: "Vanuatu", code: "+678", abb: "VU" },
  { country: "Vatican City", code: "+39-06", abb: "VA" },
  { country: "Venezuela", code: "+58", abb: "VE" },
  { country: "Vietnam", code: "+84", abb: "VN" },
  { country: "Yemen", code: "+967", abb: "YE" },
  { country: "Zambia", code: "+260", abb: "ZM" },
  { country: "Zimbabwe", code: "+263", abb: "ZW" },
];
